#!/bin/bash

# Always run the tests from this script's folder
cd $(dirname "$0") || exit 1

# Read default configuration
source _include.sh

# Run the unit tests first
python unit.py || failed=1
echo

for file in */run
do
	echo "        Running $file..."
	$file || failed=1
done

test $failed -ne 0 && GIT_PAGER= git diff .
tests_exit
