#!/bin/bash

# Always run the tests from this script's folder
cd $(dirname "$0") || exit 1

# Read default configuration
source ../_include.sh

# Test files user supplied files ($@) otherwise test everything
for file in ${@:-*.sed}
do

    # The emulator do not support GNU sed extensions
    test ${file%.gnu.sed} != $file && continue

    test_message "Testing ${file%.sed}"

    # Run the same sed script in sed and sedsed -d, results must be equal
    echo "$text" | $sed -f $file > $sed_output || failed=1
    echo "$text" | $sedsed --emu -f $file > $sedsed_output || failed=1
    diff -U1 $sed_output $sedsed_output || failed=1
done

tests_clean_up
tests_exit
