### foo
#foo
#
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:/foo/ {
#--------------------------------------------------
/foo/ {
# c1
		i\
COMM:c\\\\N1 - allowed without 
#--------------------------------------------------
c\
1 - allowed without 
# foo;bar
#;
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:p
#--------------------------------------------------
p
#p1
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:p
#--------------------------------------------------
p
# p2
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:p
#--------------------------------------------------
p
### p3
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:p
#--------------------------------------------------
p
# p4
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:p
#--------------------------------------------------
p
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:p
#--------------------------------------------------
p
# p5
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:s/a/b/
#--------------------------------------------------
s/a/b/
#s1
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:s/a/b/
#--------------------------------------------------
s/a/b/
# s2
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:s/a/b/gp
#--------------------------------------------------
s/a/b/gp
#s3
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:s/a/b/gp
#--------------------------------------------------
s/a/b/gp
# s4
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM::foo
#--------------------------------------------------
:foo
#l1
		i\
COMM::foo
#--------------------------------------------------
:foo
# l2
		i\
COMM:b foo
#--------------------------------------------------
b foo
#b1
		i\
COMM:b foo
#--------------------------------------------------
b foo
# b2
		i\
COMM:b 
#--------------------------------------------------
b 
#b3
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:b 
#--------------------------------------------------
b 
# b4
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:}
#--------------------------------------------------
}
# c2
#
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x

# Debugged SED script generated by sedsed (https://aurelio.net/projects/sedsed/)
