#! /bin/sed -f 
# fmt.sed -- format text such as each line gets below 40 chars
# $Id: fmt.sed,v 1.1 1998/05/28 04:21:33 cdua Exp $ 
# Carlos Duarte, 980528
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM::a
#--------------------------------------------------
:a
		i\
COMM:/^.\\{40\\}/ !{
#--------------------------------------------------
/^.\{40\}/ !{
		i\
COMM:$ q
#--------------------------------------------------
$ q
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:N
#--------------------------------------------------
N
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:s/ *\\n */ /
#--------------------------------------------------
s/ *\n */ /
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:b a
#--------------------------------------------------
b a
		i\
COMM:}
#--------------------------------------------------
}
		i\
COMM:s/^.\\{40\\}/&\\\\N/
#--------------------------------------------------
s/^.\{40\}/&\
/
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:s/^\\(.*\\) \\(.*\\)\\n/\\1\\\\N\\2/
#--------------------------------------------------
s/^\(.*\) \(.*\)\n/\1\
\2/
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:P
#--------------------------------------------------
P
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:s/^.*\\n//
#--------------------------------------------------
s/^.*\n//
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:b a
#--------------------------------------------------
b a
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x

# Debugged SED script generated by sedsed (http://aurelio.net/projects/sedsed/)
