		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:\\,addr1,,// !s/a/./gpw w.out1
		\,addr1,y/!/!/
#--------------------------------------------------
\,addr1,,// !s/a/./gpw w.out1
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x

# Debugged SED script generated by sedsed (https://aurelio.net/projects/sedsed/)
