# Google Code issue #3: https://code.google.com/p/sedsed/issues/detail?id=3
# "I" char removed when appears after "/"
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:s/Ione/FAIL/
#--------------------------------------------------
s/Ione/FAIL/
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x

# Debugged SED script generated by sedsed-1.1-dev (http://aurelio.net/projects/sedsed/)
