#n
#! /bin/sed -nf
# These three reverse the lines in a file by moving the line to
# the *beginning* of hold space.  Replace these three with a `p'
# (or remove them and remove the -n flag above) to reverse
# the chars on a single line
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:1 !G
#--------------------------------------------------
1 !G
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:h
#--------------------------------------------------
h
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x
		i\
COMM:$ p
#--------------------------------------------------
$ p
		s/^/PATT:/
		l
		s/^PATT://
		x
		s/^/HOLD:/
		l
		s/^HOLD://
		x

# Debugged SED script generated by sedsed (http://aurelio.net/projects/sedsed/)
