#!/bin/bash

# Always run the tests from this script's folder
cd $(dirname "$0") || exit 1

# Read default configuration
source  ../_include.sh

# Test files user supplied files ($@) otherwise test everything
for file_path in ${@:-../scripts/*.sed ../parsing/*.sed}; do

	output_file=$(basename $file_path)

	# Generate the debug file
	test_message "Generating $output_file"
	$sedsed --dump-debug -f $file_path > $output_file
done

tests_git_status
