language: python

# Supported Python versions
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  # The test suite needs a gsed command
  - ln -s /bin/sed ~/bin/gsed

  # Install sedparse
  - pip install --quiet -r requirements.txt

  # Only run pylint/black in newer Python versions
  - case $TRAVIS_PYTHON_VERSION in 3.6)
    pip install --quiet -r requirements-dev.txt;;
    esac

script:
  - case $TRAVIS_PYTHON_VERSION in 3.6)
    pylint *.py test/*.py;;
    esac
  - case $TRAVIS_PYTHON_VERSION in 3.6)
    black --check -S *.py test/*.py;;
    esac
  - ./ci/shellcheck
  - ./test/run

### Environment
# Ubuntu 14.04.5 LTS
# /bin/sed v4.2.2
# uid=2000(travis) groups=2000(travis),999(docker)
# PWD=/home/travis/build/aureliojargas/sedsed
# PATH=/home/travis/bin
#      /home/travis/.local/bin
#      /usr/local/sbin
#      /usr/local/bin
#      /usr/sbin
#      /usr/bin
#      /sbin
#      /bin
