language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - if test $TRAVIS_PYTHON_VERSION = 3.6; then pip install -q pylint; fi
  - ln -s /bin/sed ~/bin/gsed
script:
  - if test $TRAVIS_PYTHON_VERSION = 3.6; then pylint sedsed.py; fi
  - ./ci/shellcheck
  - ./test/run

### Environment
# Ubuntu 14.04.5 LTS
# /bin/sed v4.2.2
# uid=2000(travis) groups=2000(travis),999(docker)
# PWD=/home/travis/build/aureliojargas/sedsed
# PATH=/home/travis/bin
#      /home/travis/.local/bin
#      /usr/local/sbin
#      /usr/local/bin
#      /usr/sbin
#      /usr/bin
#      /sbin
#      /bin
