#!/bin/bash

# Always run the tests from this script's folder
cd $(dirname "$0") || exit 1

# Read default configuration
source  ../_include.sh

# Test files user supplied files ($@) otherwise test everything
for file_path in ${@:-../emu/*.sed}
do

    file=$(basename $file_path)
	output_file=$file.txt

	test_message "Testing ${file%.sed}"

	# Run the sed emulator debugger and save the results
	echo "$text" | $sedsed --emudebug -f $file_path > $output_file
done

tests_git_status
