#!/bin/bash

# Always run the tests from this script's folder
cd $(dirname "$0") || exit 1

# Read default configuration
source ../_include.sh

# Test files user supplied files ($@) otherwise test everything
for file_path in ${@:-../scripts/*.sed}
do

    output_file=$(basename $file_path)

    # Generate the indented version
    test_message "Generating $output_file"
    $sedsed --indent -f $file_path > $output_file || failed=1
done

tests_git_status
tests_exit
