#!/bin/bash
# Run shellcheck in every shell script in this repo

set -euo pipefail

# Always run this script in its folder
cd "$(dirname "$0")" || exit 1

# This include file needs a special option
file=../test/_include.sh
echo "Checking $file"
shellcheck --shell bash --exclude SC2034 "$file"

# Check all the other scripts
find .. -name run -o -name run.sh |
    while read -r file
    do
        echo "Checking $file"
        (cd "$(dirname "$file")"; shellcheck -x --exclude SC2068 "$(basename "$file")")
        # Note: cd is necessary so the included file will be found
    done
